/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/xe/gun/type Volume
/xe/gun/shape Cylinder
/xe/gun/radius 260 mm
/xe/gun/halfz 525 mm
/xe/gun/center 0 0 75 mm
/xe/gun/confine TeflonSideVetoLining* TeflonPanel* LowerTeflonPanel* TeflonRods* TopPmtTeflonHolder*

/xe/gun/particle neutron
/xe/gun/energytype Spectrum
/xe/gun/energyspectrum /home/physik/alexkish/geant4/Xe100/macros/spectra/teflon_Th.dat
