/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# detector parameters
/Xe/detector/setLXeScintillation 1
/Xe/detector/setTeflonReflectivity 0.95
/Xe/detector/setLXeAbsorbtionLength 5. m
/Xe/detector/setLXeRayScatterLength 50.0 cm

/xe/gun/particle alpha
/xe/gun/energytype Mono
/xe/gun/energy 10. keV
/xe/gun/angtype direction
/xe/gun/type Volume
/xe/gun/shape Cylinder
/xe/gun/radius 152.4 mm
/xe/gun/center 0 0 -153.75 mm
/xe/gun/halfz 157.25 mm
/xe/gun/direction 0 0 -1
